namespace: my_own_namespace
name: yandex_cloud_elk
version: 1.0.0
readme: README.md
authors:
  - Chipy1 (@Chipy1)
description: Collection with my_own_module and my_own_role
license:
  - MIT
tags:
  - file
  - module
  - homework
dependencies: {}
repository: https://github.com/Chipy1/my_own_collection
documentation: https://github.com/Chipy1/my_own_collection
homepage: https://github.com/Chipy1/my_own_collection
issues: https://github.com/Chipy1/my_own_collection/issues
build_ignore: []
